name: Export User and Password

on:
  workflow_dispatch:
    inputs:
      user:
        description: 'Faceless User'
        required: true
        default: 'default_user'
      password:
        description: 'Faceless User Password'
        required: true
        default: 'default_password'
      tool_user:
        description: 'Tool User'
        required: true
        default: 'tool_default_user'
      tool_pass:
        description: 'Tool Password'
        required: true
        default: 'tool_default_password'

jobs:
  export_vars:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Mask Sensitive Inputs using Python
        shell: bash
        run: |
          python3 - <<EOF
          
          import os
          # Retrieve sensitive data from GitHub Actions inputs
          user = os.getenv('BINDUSER')
          password = os.getenv('BINDPASSWORD')
          tool_user = os.getenv('TOOLUSER')
          tool_password = os.getenv('TOOLPASS')
          
          # Mask sensitive values by printing them in a masked form
          def mask_sensitive_data(data):
              if data is None:
                  return "None"  # Or you can return an empty string or some other indicator
              return '*' * len(data)
          
          # Mask the inputs
          masked_user = mask_sensitive_data(user)
          masked_password = mask_sensitive_data(password)
          masked_tool_user = mask_sensitive_data(tool_user)
          masked_tool_password = mask_sensitive_data(tool_password)
          
          # Print the masked values
          print(f"Masked User: {masked_user}")
          print(f"Masked Password: {masked_password}")
          print(f"Masked Tool User: {masked_tool_user}")
          print(f"Masked Tool Password: {masked_tool_password}")
          EOF
        env:
          BINDUSER: ${{ github.event.inputs.user }}
          BINDPASSWORD: ${{ github.event.inputs.password }}
          TOOLUSER: ${{ github.event.inputs.tool_user }}
          TOOLPASS: ${{ github.event.inputs.tool_pass }}
         

      # - name: Export faceless user and password
      #   shell: bash
      #   run: |
        
      #     # # # Retrieve inputs
      #     # # echo "BINDUSER=${{ github.event.inputs.user }}" >> $GITHUB_ENV
      #     # # echo "BINDPASSWORD=${{ github.event.inputs.password }}" >> $GITHUB_ENV
      #     # # echo "TOOLUSER=${{ github.event.inputs.tool_user }}" >> $GITHUB_ENV
      #     # # echo "TOOLPASS=${{ github.event.inputs.tool_pass }}" >> $GITHUB_ENV
      #     # w
          
      #     # Mask sensitive values
      #     echo "::add-mask::${{ github.event.inputs.user }}"
      #     echo "::add-mask::${{ github.event.inputs.password }}"
      #     echo "::add-mask::${{ github.event.inputs.tool_user }}"
      #     echo "::add-mask::${{ github.event.inputs.tool_pass }}"
          
      - name: Run Python script
        shell: bash
        env:
          BINDUSER: ${{ github.event.inputs.user }}
          BINDPASSWORD: ${{ github.event.inputs.password }}
          TOOLUSER: ${{ github.event.inputs.tool_user }}
          TOOLPASS: ${{ github.event.inputs.tool_pass }}
        run: |
          python3 pass_validate.py
