name: Export User and Password

on:
  workflow_dispatch:
    inputs:
      user:
        description: 'Faceless User'
        required: true
        default: 'default_user'
      password:
        description: 'Faceless User Password'
        required: true
        default: 'default_password'
      tool_user:
        description: 'Tool User'
        required: true
        default: 'tool_default_user'
      tool_pass:
        description: 'Tool Password'
        required: true
        default: 'tool_default_password'

jobs:
  export_vars:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Export faceless user and password
        shell: powershell
        run: |
          # Using Here-String to handle special characters and preserve the raw input
          $rawUser = @"
          ${{ github.event.inputs.user }}
          "@

          $rawPassword = @"
          ${{ github.event.inputs.password }}
          "@
          
          $rawToolUser = @"
          ${{ github.event.inputs.tool_user }}
          "@
          
          $rawToolPass = @"
          ${{ github.event.inputs.tool_pass }}
          "@
          
          # Masking sensitive values
          echo "::add-mask::${{ github.event.inputs.user }}"
          echo "::add-mask::${{ github.event.inputs.password }}"
          echo "::add-mask::${{ github.event.inputs.tool_user }}"
          echo "::add-mask::${{ github.event.inputs.tool_pass }}"
          
      - name: Run Python script
        shell: powershell
        env:
          BINDUSER: ${{ github.event.inputs.user }}
          BINDPASSWORD: ${{ github.event.inputs.password }}
          TOOLUSER: ${{ github.event.inputs.tool_user }}
          TOOLPASS: ${{ github.event.inputs.tool_pass }}
        run: |
          python pass_validate.py
