name: Export User and Password

on:
  workflow_dispatch:
    inputs:
      user:
        description: 'Faceless User'
        required: true
        default: 'default_user'
      password:
        description: 'Faceless User Password'
        required: true
        default: 'default_password'
      tool_user:
        description: 'Tool User'
        required: true
        default: 'tool_default_user'
      tool_pass:
        description: 'Tool Password'
        required: true
        default: 'tool_default_password'

jobs:
  export_vars:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Export faceless user and password
        shell: bash
        run: |
          # Retrieve inputs
          rawUser=$(printf '%s' "${{ github.event.inputs.user }}")
          rawPassword=$(printf '%s' "${{ github.event.inputs.password }}")
          rawToolUser=$(printf '%s' "${{ github.event.inputs.tool_user }}")
          rawToolPass=$(printf '%s' "${{ github.event.inputs.tool_pass }}")

          # Mask sensitive values
          echo "::add-mask::${rawUser}"
          echo "::add-mask::${rawPassword}"
          echo "::add-mask::${rawToolUser}"
          echo "::add-mask::${rawToolPass}"

      - name: Run Python script
        shell: bash
        env:
          BINDUSER: ${{ github.event.inputs.user }}
          BINDPASSWORD: ${{ github.event.inputs.password }}
          TOOLUSER: ${{ github.event.inputs.tool_user }}
          TOOLPASS: ${{ github.event.inputs.tool_pass }}
        run: |
          python3 pass_validate.py
